'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils/cn';

/**
 * The two buildings, presented as a pair.
 *
 * Both already sit in the main navigation, so this is not about
 * reachability — it is about relationship. As two separate menu entries the
 * residence and the tower read as unrelated pages; side by side in one
 * control they read as what they are: two buildings generated by the same
 * system, which is the actual thing being demonstrated. A visitor who
 * switches between them has understood the product without being told.
 */
const BUILDINGS = [
  { label: 'Residence', href: '/experience', note: 'Single dwelling' },
  { label: 'Oceanfront Tower', href: '/tower', note: 'Twenty storeys' },
] as const;

export function BuildingSwitch({ className }: { className?: string }) {
  const pathname = usePathname();

  return (
    <nav
      aria-label="Choose a building"
      className={cn(
        'border-alabaster/15 bg-obsidian/60 inline-flex border backdrop-blur-md',
        className,
      )}
    >
      {BUILDINGS.map((building) => {
        const current = pathname === building.href;
        return (
          <Link
            key={building.href}
            href={building.href}
            data-cursor="link"
            aria-current={current ? 'page' : undefined}
            className={cn(
              'ease-luxe flex flex-col gap-0.5 px-4 py-2.5 transition-colors duration-300 sm:px-5',
              current ? 'bg-alabaster/10' : 'hover:bg-alabaster/5',
            )}
          >
            <span
              className={cn(
                'text-eyebrow uppercase',
                current ? 'text-gold' : 'text-mist hover:text-alabaster',
              )}
            >
              {building.label}
            </span>
            {/* Brighter on the selected item: the tint behind it lifts the
                ground, and `stone` that clears 4.5:1 on the obsidian page
                does not clear it against this lighter panel. */}
            <span
              className={cn(
                'hidden text-[0.625rem] tracking-[0.18em] uppercase sm:block',
                current ? 'text-mist' : 'text-stone',
              )}
            >
              {building.note}
            </span>
          </Link>
        );
      })}
    </nav>
  );
}

export default BuildingSwitch;
