/**
 * The finishes the residence is actually built from. Every entry below
 * corresponds to a material in `lib/three/materials.ts` that the model
 * renders with — this is a schedule of what you are looking at, not a
 * mood board written to fill a page.
 */
export type Finish = {
  name: string;
  where: string;
  note: string;
};

export const PALETTE: readonly Finish[] = [
  {
    name: 'Honed limestone',
    where: 'Plinth, terrace, pool coping, interior floors',
    note: 'Warm off-white, quarried in large format and laid without a border.',
  },
  {
    name: 'Fair-faced concrete',
    where: 'Structural frame, soffits, parapets',
    note: 'Cast in place and left as struck; the formwork grain is the finish.',
  },
  {
    name: 'Dark timber',
    where: 'Entrance leaf, joinery, bedroom floors',
    note: 'Vertical grain on the pivot door, running its full height.',
  },
  {
    name: 'Bronze',
    where: 'Hardware, rails, lighting fixtures',
    note: 'Satin rather than polished, so it reads as weight and not as trim.',
  },
  {
    name: 'Architectural glazing',
    where: 'Living wall, cantilever, foyer laylight',
    note: 'Slim frames set deep in the reveal, so the glass sits in shadow.',
  },
  {
    name: 'Book-matched marble',
    where: 'Island, vanities, fireplace surround',
    note: 'Veining drawn across each slab rather than repeated between them.',
  },
] as const;

/**
 * The same six finishes, relocated to the tower.
 *
 * `resolveLighting`, the material library, and every one of these finishes
 * are shared between the two buildings — the tower's whole point is that
 * it is generated by the same system, not a second one built to match. The
 * `note` on each is the same description of the material itself; only
 * `where` changes, because a bronze rail means something different on a
 * balcony fin than it does on a stair.
 */
const TOWER_WHERE: Record<(typeof PALETTE)[number]['name'], string> = {
  'Honed limestone': 'Podium plinth, colonnade columns, retail floors',
  'Fair-faced concrete': 'Podium banding, structural frame',
  'Dark timber': 'Apartment joinery, the fluted media wall, bedroom headboards',
  Bronze: 'Balcony fins, balustrade rails, apartment hardware',
  'Architectural glazing': 'Curtain-wall bays, balcony balustrades, the atrium roof light',
  'Book-matched marble': 'Apartment kitchen islands, bathroom vanities',
};

export const TOWER_PALETTE: readonly Finish[] = PALETTE.map((finish) => {
  const where = TOWER_WHERE[finish.name];
  if (!where) throw new Error(`no tower location recorded for finish ${finish.name}`);
  return { ...finish, where };
});
