import { readFile } from 'node:fs/promises';
import path from 'node:path';

import {
  PDFDocument,
  StandardFonts,
  rgb,
  type PDFFont,
  type PDFImage,
  type PDFPage,
} from 'pdf-lib';

import { CLIENT } from '@/lib/constants/client';
import { PROPERTY } from '@/lib/constants/site';
import { PALETTE } from '@/lib/experience/palette';
import { brochureFigures } from '@/lib/property/brochure';

/**
 * The downloadable brochure, assembled at build time.
 *
 * ## Why a route and not a file in `public/`
 *
 * A PDF checked into `public/` is a photocopy: correct on the day it is
 * made and wrong from the first time somebody moves a partition. This one
 * is built from `lib/property/brochure.ts`, which counts the same room
 * schedule the 3D model is generated from — so the interior area in the
 * document a buyer downloads cannot disagree with the interior area on the
 * page they downloaded it from. `force-static` means Next renders it once
 * during `next build` and serves the bytes from the CDN afterwards: a fresh
 * document every deploy, at no per-request cost.
 *
 * ## Why the photography is not rendered here
 *
 * The plates are frames of the actual model, but they are captured by
 * `scripts/brochure-stills.mjs` and committed, not rendered during the
 * build. Vercel's builder has no GPU; the scene would go through a software
 * rasteriser at roughly half a minute a frame on a machine that has to
 * install a browser first. `scripts/brochure-stills.mjs` explains the
 * trade-off in full. They are the same class of artefact as the Blender
 * furniture in `public/assets/models/` — generated by a documented script,
 * committed, regenerated when the source changes.
 */
export const dynamic = 'force-static';

const A4 = { width: 595.28, height: 841.89 };
const MARGIN = 48;
const CONTENT = A4.width - MARGIN * 2;

/** Drawn from the same palette the site is built in. */
const INK = rgb(0.13, 0.12, 0.11);
const MUTED = rgb(0.45, 0.43, 0.4);
const RULE = rgb(0.82, 0.8, 0.76);
const PAPER = rgb(0.98, 0.97, 0.96);

/** Captured by `scripts/brochure-stills.mjs`, which names the same spaces. */
const PLATES = {
  living: { file: 'living.jpg', caption: 'Living room' },
  pool: { file: 'pool.jpg', caption: 'Infinity edge above the coast' },
  master: { file: 'master.jpg', caption: 'Master suite' },
} as const;

/**
 * The disclosure, verbatim from `lib/constants/site.ts`.
 *
 * A brochure travels further than the site does and arrives without its
 * context, so it is the last document that should soften this. It is the
 * project's existing sentence, not a new one written for print.
 */
const DISCLOSURE =
  'AURELIA is a conceptual residence — an architectural proposition presented as an ' +
  'experience, built to be adapted to a real listing. The residence, its setting and the ' +
  'studio credited below are part of that proposition and describe no existing property ' +
  'or practice.';

/** Letter-spaced small caps, the site's own label treatment. */
function drawEyebrow(page: PDFPage, text: string, x: number, y: number, font: PDFFont, size = 7.5) {
  let cursor = x;
  for (const character of text.toUpperCase()) {
    page.drawText(character, { x: cursor, y, size, font, color: MUTED });
    cursor += font.widthOfTextAtSize(character, size) + size * 0.22;
  }
}

/** Greedy wrap, separated from drawing so a block can be measured first. */
function wrapText(text: string, font: PDFFont, size: number, width: number): string[] {
  const lines: string[] = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) > width && line) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/** Draws a wrapped block from `y` downward and returns the next free y. */
function drawParagraph(
  page: PDFPage,
  text: string,
  options: {
    x: number;
    y: number;
    width: number;
    font: PDFFont;
    size: number;
    leading: number;
    color?: ReturnType<typeof rgb>;
  },
): number {
  const { x, width, font, size, leading } = options;
  const color = options.color ?? INK;
  let y = options.y;
  for (const line of wrapText(text, font, size, width)) {
    page.drawText(line, { x, y, size, font, color });
    y -= leading;
  }
  return y;
}

/**
 * A plate at its own aspect ratio, sitting on `bottom` with its caption
 * beneath it. Anchoring to the foot of the page rather than flowing from
 * the text above keeps the images on a common baseline across the spread —
 * the copy above them is what varies in length, not the photography.
 */
function drawPlate(page: PDFPage, image: PDFImage, caption: string, font: PDFFont, bottom: number) {
  const height = (CONTENT * image.height) / image.width;
  page.drawText(caption, { x: MARGIN, y: bottom, size: 8, font, color: MUTED });
  page.drawImage(image, { x: MARGIN, y: bottom + 14, width: CONTENT, height });
}

async function plate(file: string): Promise<Buffer | null> {
  try {
    return await readFile(path.join(process.cwd(), 'public', 'assets', 'brochure', file));
  } catch (error) {
    console.warn(`[brochure] missing plate ${file}:`, error);
    return null;
  }
}

export async function GET(): Promise<Response> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const { property } = CLIENT;
  pdf.setTitle(`${property.name} — ${property.location}`);
  pdf.setSubject(property.statement);
  pdf.setProducer('AURELIA');

  // --- Cover -------------------------------------------------------------
  const cover = pdf.addPage([A4.width, A4.height]);
  cover.drawRectangle({ x: 0, y: 0, width: A4.width, height: A4.height, color: PAPER });

  // Full bleed down to the title block: scaled to the height it has to
  // fill and centred, so the overflow is cropped off the sides rather than
  // leaving the bottom third of the cover empty.
  const arrivalBuffer = await plate('arrival.jpg');
  if (arrivalBuffer) {
    try {
      const arrival = await pdf.embedJpg(arrivalBuffer);
      const coverTop = 268;
      const coverHeight = A4.height - coverTop;
      const coverWidth = (coverHeight * arrival.width) / arrival.height;
      cover.drawImage(arrival, {
        x: (A4.width - coverWidth) / 2,
        y: coverTop,
        width: coverWidth,
        height: coverHeight,
      });
    } catch (error) {
      console.warn('[brochure] failed to embed arrival.jpg', error);
    }
  }

  let y = 268 - 56;
  drawEyebrow(cover, property.collection, MARGIN, y, regular);
  y -= 30;
  cover.drawText(property.name, { x: MARGIN, y, size: 26, font: bold, color: INK });
  y -= 20;
  cover.drawText(property.location, { x: MARGIN, y, size: 11, font: regular, color: MUTED });
  y -= 34;
  drawParagraph(cover, property.statement, {
    x: MARGIN,
    y,
    width: CONTENT * 0.8,
    font: regular,
    size: 12,
    leading: 18,
  });

  // --- Specification -----------------------------------------------------
  const spec = pdf.addPage([A4.width, A4.height]);
  spec.drawRectangle({ x: 0, y: 0, width: A4.width, height: A4.height, color: PAPER });
  y = A4.height - MARGIN - 20;
  drawEyebrow(spec, 'Specification', MARGIN, y, regular);
  y -= 34;

  for (const figure of brochureFigures()) {
    spec.drawText(figure.label, { x: MARGIN, y, size: 10, font: bold, color: INK });
    spec.drawText(figure.note, { x: MARGIN + 110, y, size: 9, font: regular, color: MUTED });
    const valueWidth = regular.widthOfTextAtSize(figure.value, 10);
    spec.drawText(figure.value, {
      x: A4.width - MARGIN - valueWidth,
      y,
      size: 10,
      font: regular,
      color: INK,
    });
    y -= 12;
    spec.drawLine({
      start: { x: MARGIN, y },
      end: { x: A4.width - MARGIN, y },
      thickness: 0.5,
      color: RULE,
    });
    y -= 18;
  }

  const livingBuffer = await plate(PLATES.living.file);
  if (livingBuffer) {
    try {
      const living = await pdf.embedJpg(livingBuffer);
      drawPlate(spec, living, PLATES.living.caption, regular, MARGIN);
    } catch (error) {
      console.warn(`[brochure] failed to embed ${PLATES.living.file}`, error);
    }
  }

  // --- Materials ---------------------------------------------------------
  const materials = pdf.addPage([A4.width, A4.height]);
  materials.drawRectangle({ x: 0, y: 0, width: A4.width, height: A4.height, color: PAPER });
  y = A4.height - MARGIN - 20;
  drawEyebrow(materials, 'Materials', MARGIN, y, regular);
  y -= 34;

  for (const finish of PALETTE) {
    materials.drawText(finish.name, { x: MARGIN, y, size: 10, font: bold, color: INK });
    y -= 14;
    materials.drawText(finish.where, { x: MARGIN, y, size: 8.5, font: regular, color: MUTED });
    y -= 15;
    y = drawParagraph(materials, finish.note, {
      x: MARGIN,
      y,
      width: CONTENT * 0.72,
      font: regular,
      size: 9.5,
      leading: 14,
    });
    y -= 12;
  }

  const poolBuffer = await plate(PLATES.pool.file);
  if (poolBuffer) {
    try {
      const pool = await pdf.embedJpg(poolBuffer);
      drawPlate(materials, pool, PLATES.pool.caption, regular, MARGIN);
    } catch (error) {
      console.warn(`[brochure] failed to embed ${PLATES.pool.file}`, error);
    }
  }

  // --- Closing plate and disclosure -------------------------------------
  const closing = pdf.addPage([A4.width, A4.height]);
  closing.drawRectangle({ x: 0, y: 0, width: A4.width, height: A4.height, color: PAPER });

  const channels = [CLIENT.agent.email, CLIENT.agent.phoneDisplay ?? CLIENT.agent.phone].filter(
    Boolean,
  ) as string[];
  const disclosureLines = wrapText(DISCLOSURE, regular, 8, CONTENT);

  let foot = MARGIN;
  drawEyebrow(closing, `${PROPERTY.architect} · ${PROPERTY.year}`, MARGIN, foot, regular);
  foot += 22;
  drawParagraph(closing, DISCLOSURE, {
    x: MARGIN,
    y: foot + (disclosureLines.length - 1) * 12,
    width: CONTENT,
    font: regular,
    size: 8,
    leading: 12,
    color: MUTED,
  });
  foot += disclosureLines.length * 12 + 14;
  if (channels.length > 0) {
    closing.drawText(channels.join('   ·   '), {
      x: MARGIN,
      y: foot,
      size: 10,
      font: regular,
      color: INK,
    });
    foot += 30;
  }

  const masterBuffer = await plate(PLATES.master.file);
  if (masterBuffer) {
    try {
      const master = await pdf.embedJpg(masterBuffer);
      const masterHeight = (CONTENT * master.height) / master.width;
      drawPlate(
        closing,
        master,
        PLATES.master.caption,
        regular,
        A4.height - MARGIN - masterHeight - 14,
      );
    } catch (error) {
      console.warn(`[brochure] failed to embed ${PLATES.master.file}`, error);
    }
  }

  const bytes = await pdf.save();
  return new Response(Buffer.from(bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="aurelia-residence.pdf"',
      'Cache-Control': 'public, max-age=0, must-revalidate',
    },
  });
}
