import { createHash } from 'node:crypto';
import { copyFile, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { CUBE_FACES } from './cubemap-faces.mjs';

/**
 * Emits the panorama manifest from what is actually on disk.
 *
 * Two rules shape this file:
 *
 *  - **A missing room is not an error.** Renders run per room and take
 *    minutes each, so "some rooms done" is the normal state of the output
 *    directory, not an edge case. A room whose faces are absent is skipped
 *    and reported.
 *  - **A partial run must not erase the rest.** `render-panoramas` takes a
 *    single room id, which is how it will usually be run. Emitting only that
 *    room's entry would delete twelve others from the site.
 */

/**
 * Content hash of the six faces, in fixed order. Goes in the directory path
 * rather than the filename, so the URL is immutable while `id` — the
 * loader's cache key — stays the space id across rebuilds.
 *
 * Note what this implies and what caught it: the hash names a directory that
 * does not exist until something creates it. The render job writes to
 * `latest/`, so recording `/<id>/<hash>` without publishing the faces there
 * produces a manifest whose every URL 404s — six faces at a time, silently,
 * with the manifest looking entirely correct. `publish()` below is what
 * closes that gap.
 */
async function hashRoom(dir, extension) {
  const digest = createHash('sha256');
  for (const face of CUBE_FACES) {
    try {
      digest.update(await readFile(join(dir, `${face}.${extension}`)));
    } catch {
      // Any face missing means the room is not rendered. A partial face set
      // is worse than none: five faces and a hole reads as a torn room.
      return null;
    }
  }
  return digest.digest('hex').slice(0, 12);
}

/**
 * Copies the six faces to their immutable hashed directory and clears out
 * any previous ones.
 *
 * A copy rather than a rename: `latest/` stays the working directory the
 * render job swaps atomically, and the hashed directory is the published
 * artifact. Old hashes are pruned because they are otherwise never reachable
 * again — the manifest only ever names the current one.
 */
async function publish(roomDir, hash, extension) {
  const target = join(roomDir, hash);
  await mkdir(target, { recursive: true });
  for (const face of CUBE_FACES) {
    const name = `${face}.${extension}`;
    await copyFile(join(roomDir, 'latest', name), join(target, name));
  }

  for (const entry of await readdir(roomDir)) {
    if (entry === 'latest' || entry === hash || entry.startsWith('.')) continue;
    await rm(join(roomDir, entry), { recursive: true, force: true });
  }
}

function render(entries) {
  const sorted = [...entries].sort((a, b) => a.id.localeCompare(b.id));
  return (
    `// GENERATED by scripts/render-panoramas.mjs — do not edit.\n` +
    `// Regenerate with: npm run render:panoramas\n\n` +
    `import type { ManifestEntry } from './manifest-types';\n\n` +
    `export const PANORAMA_MANIFEST: readonly ManifestEntry[] = ${JSON.stringify(
      sorted,
      null,
      2,
    )};\n`
  );
}

/** Entries already recorded, so a single-room run does not wipe the others. */
async function readExisting(outFile) {
  try {
    const source = await readFile(outFile, 'utf8');
    const match = source.match(/PANORAMA_MANIFEST: readonly ManifestEntry\[\] = ([\s\S]*?);\n$/);
    return match ? JSON.parse(match[1]) : [];
  } catch {
    return [];
  }
}

export async function emitManifest(options) {
  const existing = new Map((await readExisting(options.outFile)).map((entry) => [entry.id, entry]));

  const written = [];
  const skipped = [];

  for (const id of options.spaceIds) {
    const roomDir = join(options.root, id);
    const hash = await hashRoom(join(roomDir, 'latest'), options.extension);
    if (hash === null) {
      skipped.push(id);
      // Leave any previously recorded entry alone: this run did not render
      // the room, which is not the same as the room having been removed.
      continue;
    }

    await publish(roomDir, hash, options.extension);

    existing.set(id, {
      id,
      hash,
      basePath: `${options.publicPrefix}/${id}/${hash}`,
      extension: options.extension,
      size: options.size,
    });
    written.push(id);
  }

  await writeFile(options.outFile, render([...existing.values()]), 'utf8');
  return { written, skipped };
}
