#!/usr/bin/env node
/**
 * Renders the brochure's photography.
 *
 * There is no photography — there is no building — so these are frames of
 * the actual model, captured from framings the site itself uses. Run this
 * when the geometry or the materials change:
 *
 *   npm run build && node scripts/brochure-stills.mjs
 *
 * ## Why this is a script and not part of the build
 *
 * The obvious thing is to render these during `next build` so they can
 * never go stale. It is not practical here, and the reason is hardware:
 * Vercel's build has no GPU, so the scene would have to go through
 * SwiftShader, a software rasteriser. This project's villa is a few hundred
 * thousand triangles with shadow maps and post-processing, and one frame
 * takes the better part of half a minute that way. Four frames is two
 * minutes of build time added to every deploy, on a machine that also has
 * to install a ~300 MB browser first. A deploy that occasionally times out
 * is worse than a brochure that is regenerated deliberately.
 *
 * So this follows the pattern the repository already uses for the Blender
 * furniture: `tools/blender/models.py` writes .glb files into
 * `public/assets/models/`, they are committed, and they are regenerated by
 * running the script when the source changes. These are the same kind of
 * artefact.
 *
 * The PDF itself is NOT pre-rendered — `app/brochure/route.ts` builds it
 * from the live room schedule at build time, so the figures in it cannot
 * drift from the figures on the site.
 */
import { spawn } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { chromium } from 'playwright';
import { ALL_PLATES, OUT_DIR, TOWER_PLATES } from './plates.manifest.mjs';

const PORT = Number(process.env.BROCHURE_PORT ?? 3910);
const ORIGIN = `http://127.0.0.1:${PORT}`;
const OUT = OUT_DIR;

/**
 * The framings, and how each is captured.
 *
 * The list itself lives in `scripts/plates.manifest.mjs` — the capture
 * script, the test that checks the ids are real, and anyone deciding what
 * still needs rendering all read the same rows. It used to be four plates
 * written here; it is now every residence space and every tower framing,
 * because the gallery shows all of them and a tile with no plate is a
 * visibly empty cell.
 *
 * Two capture paths, because the two buildings genuinely differ:
 *
 * - The residence goes through the gallery's own lightbox, by clicking the
 *   tile a visitor would click. That is the one surface on the site which
 *   already path-traces, so the capture exercises the real path end to end.
 *
 * - The tower has no lightbox. It is captured from the walkthrough itself
 *   on the framing `?step=` selects, which path-traces only while
 *   `window.__AURELIA_STILL_SAMPLES__` is set — the same hook the lightbox
 *   reads, set here and nowhere else. No capture-only route exists to
 *   drift away from what the site renders.
 */

/**
 * The sample budget.
 *
 * 320 is `PathTracer`'s own default and what the scene is tuned for: on a
 * real GPU it converges in a couple of seconds, and it is the figure the
 * plates should be rendered at, because the finishing pass reads the
 * traced frame's materials and lighting — a noisier base gives it less to
 * work from.
 *
 * ## It will not converge without a GPU
 *
 * This was 90 for exactly that reason. Every sample goes through
 * SwiftShader's software rasteriser on a machine with no GPU, and 320 at
 * 3840×2160 was measured at more than forty minutes for a single plate —
 * past `CONVERGE_TIMEOUT_MS`, and across twenty-nine plates a run that
 * cannot finish. 90 fitted inside the timeout and was still real path
 * tracing rather than a rasterized fallback.
 *
 * So the default is now the GPU figure, and the software case is an
 * override rather than a silent compromise for everyone:
 *
 *   STILL_SAMPLES=90 node scripts/brochure-stills.mjs
 *
 * Getting this wrong fails loudly — the plate times out and the run stops
 * — rather than quietly writing twenty-nine noisy frames.
 */
const STILL_SAMPLES = Number(process.env.STILL_SAMPLES ?? 320);

if (!Number.isFinite(STILL_SAMPLES) || STILL_SAMPLES < 1) {
  throw new Error(`STILL_SAMPLES must be a positive number, got "${process.env.STILL_SAMPLES}"`);
}

/**
 * The capture resolution.
 *
 * 3840×2160 is what a brochure plate wants: a still someone can zoom,
 * where the live page is only ever seen in motion.
 *
 * It is four times the pixels of 1080p and roughly four times the trace,
 * which is the difference between a render that fits an evening on modest
 * hardware and one that does not. It is also more than the finishing pass
 * consumes — that returns around 1–2K — so for plates headed straight
 * through it, 1920×1080 costs nothing that survives:
 *
 *   RENDER_WIDTH=1920 RENDER_HEIGHT=1080 node scripts/brochure-stills.mjs
 *
 * Render at 4K when the plate is the final artefact; render at 1080p when
 * it is a base for the finishing pass.
 */
const RENDER_WIDTH = Number(process.env.RENDER_WIDTH ?? 3840);
const RENDER_HEIGHT = Number(process.env.RENDER_HEIGHT ?? 2160);

for (const [name, value] of [
  ['RENDER_WIDTH', RENDER_WIDTH],
  ['RENDER_HEIGHT', RENDER_HEIGHT],
]) {
  if (!Number.isFinite(value) || value < 256) {
    throw new Error(`${name} must be a number of at least 256, got "${value}"`);
  }
}

/**
 * What renders the plates.
 *
 * `gpu` is the default because that is the only thing 320 samples
 * converges on. `swiftshader` is Chromium's software rasteriser — correct
 * output, orders of magnitude slower, and the right choice only on a
 * machine with no GPU, where it belongs with `STILL_SAMPLES=90`.
 *
 * The flags used to force SwiftShader with no way to opt out, which meant
 * a GPU machine rendered in software anyway. The launch below verifies
 * what it actually got rather than trusting the flag.
 */
const RENDER_BACKEND = process.env.RENDER_BACKEND ?? 'gpu';

if (!['gpu', 'swiftshader'].includes(RENDER_BACKEND)) {
  throw new Error(`RENDER_BACKEND must be "gpu" or "swiftshader", got "${RENDER_BACKEND}"`);
}

const BACKEND_ARGS =
  RENDER_BACKEND === 'swiftshader'
    ? ['--use-gl=swiftshader', '--enable-unsafe-swiftshader']
    : // Let Chromium pick the platform's native GL, and do not let its
      // blocklist quietly drop a headless server GPU back to software.
      ['--enable-gpu', '--ignore-gpu-blocklist', '--use-angle=default'];

/**
 * How long one plate may take to converge before the run gives up.
 *
 * Generous on a GPU, where 320 samples land in seconds — this exists so a
 * plate that never converges stops the run loudly instead of hanging it.
 * Raise it with `CONVERGE_TIMEOUT_MIN` when rendering somewhere slow.
 */
const CONVERGE_TIMEOUT_MS = Number(process.env.CONVERGE_TIMEOUT_MIN ?? 25) * 60_000;

console.log(
  `${ALL_PLATES.length} plates at ${RENDER_WIDTH}x${RENDER_HEIGHT}, ${STILL_SAMPLES} samples, ${RENDER_BACKEND} backend ` +
    `(timeout ${Math.round(CONVERGE_TIMEOUT_MS / 60_000)} min/plate)\n` +
    `  no GPU? RENDER_BACKEND=swiftshader STILL_SAMPLES=90`,
);

mkdirSync(OUT, { recursive: true });

const server = spawn('npx', ['next', 'start', '--port', String(PORT)], {
  stdio: 'inherit',
  env: process.env,
});
const stop = () => !server.killed && server.kill('SIGTERM');
process.on('exit', stop);
process.on('SIGINT', () => {
  stop();
  process.exit(130);
});

async function waitForServer(timeoutMs = 120_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      if ((await fetch(ORIGIN + '/', { signal: AbortSignal.timeout(4000) })).ok) return;
    } catch {
      // not up yet
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`server did not start on ${ORIGIN}`);
}

let browser;
try {
  await waitForServer();
  browser = await chromium.launch({
    // `--no-sandbox` because this often runs as root in containers where
    // Chromium's own sandbox cannot start. The rest depends on what is
    // actually rendering — see `RENDER_BACKEND`.
    args: ['--no-sandbox', ...BACKEND_ARGS],
    ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}),
  });

  // What is actually rendering, asked of the renderer rather than assumed.
  //
  // This check exists because the flags used to force SwiftShader
  // unconditionally: on a GPU machine the run would still software-render,
  // every plate would hit the convergence timeout, and the only symptom
  // would be a rented GPU doing nothing for hours. Now the backend is
  // reported before the first plate, and asking for a GPU and silently not
  // getting one stops the run instead of burning the budget.
  {
    const probe = await browser.newPage();
    const renderer = await probe.evaluate(() => {
      const gl = document.createElement('canvas').getContext('webgl2');
      if (!gl) return 'none';
      const info = gl.getExtension('WEBGL_debug_renderer_info');
      return info ? String(gl.getParameter(info.UNMASKED_RENDERER_WEBGL)) : 'unknown';
    });
    await probe.close();
    console.log(`  renderer: ${renderer}`);

    const software = /swiftshader|llvmpipe|software/i.test(renderer);
    if (RENDER_BACKEND === 'gpu' && software) {
      throw new Error(
        `asked for the GPU backend but the renderer is "${renderer}".\n` +
          `  ${STILL_SAMPLES} samples will not converge in software — the run would time out on every plate.\n` +
          `  Either fix GPU access for Chromium, or re-run in software:\n` +
          `    RENDER_BACKEND=swiftshader STILL_SAMPLES=90 node scripts/brochure-stills.mjs`,
      );
    }
  }

  for (const plate of ALL_PLATES) {
    // At least 4K, per the site's own cinematic gallery target: a brochure
    // plate is a still someone can zoom, where the live page is seen in
    // motion, so it earns more pixels than the on-screen frame does.
    const page = await browser.newPage({
      viewport: { width: RENDER_WIDTH, height: RENDER_HEIGHT },
    });

    // The full 320-sample budget converges in a couple of seconds on a real
    // GPU, which is what it is tuned for. This machine has none — every
    // sample goes through SwiftShader's software rasteriser — and at
    // 3840×2160 that is measured in tens of minutes per hundred samples, not
    // seconds. `STILL_SAMPLES` asks for a smaller budget for exactly this
    // run, through the one hook built for it, rather than lowering the
    // default every real visitor's GPU renders at.
    //
    // Installed as an init script rather than evaluated after navigation:
    // the tower reads the hook when its scene mounts, so a value set after
    // `load` arrives too late to make that frame path-trace. An init script
    // runs before any of the page's own scripts on every document, which
    // makes the hook present for both buildings without a reload.
    await page.addInitScript((n) => {
      window.__AURELIA_STILL_SAMPLES__ = n;
    }, STILL_SAMPLES);

    // Where the trace happens differs by building — see the note above.
    // The tower's `?step=` is 1-based and derived from the manifest's own
    // order, never written down: `TowerWalkthrough` indexes `TOWER_VIEWS`
    // by it, and recording an index by hand is how a reordered array
    // silently repoints every capture.
    const towerStep =
      plate.building === 'tower'
        ? TOWER_PLATES.findIndex((entry) => entry.view === plate.view) + 1
        : 0;
    const target =
      plate.building === 'tower' ? `${ORIGIN}/tower?step=${towerStep}` : `${ORIGIN}/gallery`;
    await page.goto(target, { waitUntil: 'load', timeout: 200_000 });

    // The residence needs its tile opened to reach the lightbox that
    // traces. The tower is already on its framing and begins tracing on
    // mount, so there is nothing to click.
    if (plate.building === 'residence') {
      await page.click(`[data-space="${plate.space}"]`, { timeout: 30_000 });
    }

    // Wait for convergence rather than a fixed timer. `PathTracer` reports
    // its own sample count up through `GalleryLightbox`, which mounts
    // `[data-cinematic-progress]` for exactly as long as the trace is
    // still resolving — its removal from the DOM *is* the "done" signal.
    // Waiting for it to attach first guards against a race where tracing
    // finishes inside the couple of frames it takes Playwright to look.
    await page
      .waitForSelector('[data-cinematic-progress]', { state: 'attached', timeout: 15_000 })
      .catch(() => {});
    await page.waitForSelector('[data-cinematic-progress]', {
      state: 'detached',
      timeout: CONVERGE_TIMEOUT_MS,
    });
    // One more frame so the denoiser's final pass and the display quad's
    // cross-fade are both fully composited before the shutter.
    await page.waitForTimeout(200);

    // The canvas only. Screenshotting the page would print the dialog
    // chrome — the frame counter, the close button, the caption — across
    // the plate.
    //
    // Captured through CDP rather than Playwright's own screenshot: a
    // traced frame is still technically live (the tracer keeps rendering
    // past `maxSamples` at the same sample count), so every Playwright
    // capture path waits for a "stable" frame that never arrives and times
    // out at thirty seconds. `Page.captureScreenshot` takes the frame in
    // front of it. Strip the interface before the shutter — the canvas
    // sits inside the dialog and the caption, counter and buttons are
    // siblings of it, so clipping to the canvas alone still composites
    // them into the plate otherwise.
    await page.addStyleTag({
      content:
        'body * { visibility: hidden !important; } canvas { visibility: visible !important; }',
    });
    await page.waitForTimeout(400);

    const box = await page.evaluate(() => {
      const c = document.querySelector('canvas');
      if (!c) return null;
      const r = c.getBoundingClientRect();
      return {
        x: Math.round(r.x),
        y: Math.round(Math.max(0, r.y)),
        width: Math.round(r.width),
        height: Math.round(r.height),
        scale: 1,
      };
    });
    if (!box) throw new Error(`no canvas for ${plate.file}`);

    const cdp = await page.context().newCDPSession(page);
    const shot = await cdp.send('Page.captureScreenshot', {
      format: 'jpeg',
      quality: 92,
      clip: box,
      captureBeyondViewport: false,
    });
    writeFileSync(`${OUT}/${plate.file}`, Buffer.from(shot.data, 'base64'));
    await cdp.detach();

    console.log(`  ${plate.file.padEnd(14)} ${plate.caption}`);
    await page.close();
  }
} finally {
  await browser?.close();
  stop();
}

console.log(`\n${ALL_PLATES.length} plates written to ${OUT}`);
