import { build } from 'esbuild';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Builds the primitives into a distributable package.
 *
 * Three outputs, because a component library is all three or it is not
 * usable: the compiled components, the stylesheet those components'
 * class names resolve against, and the types a consumer codes to.
 *
 * Nothing here rewrites a component. The bundle is compiled from
 * `components/ui/*` exactly as the application imports them; the single
 * substitution is `next/link`, aliased to `src/link.tsx` because a Next
 * router cannot exist outside the app. See that file for why.
 */

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const dist = resolve(here, 'dist');

await mkdir(dist, { recursive: true });

// --- components -----------------------------------------------------------
await build({
  entryPoints: [resolve(here, 'src/index.ts')],
  outfile: resolve(dist, 'index.js'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  jsx: 'automatic',
  // React is the consumer's, never ours — two copies of React in one tree
  // is the classic way to break hooks.
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  alias: {
    'next/link': resolve(here, 'src/link.tsx'),
    '@': root,
  },
  logLevel: 'warning',
});

// --- stylesheet -----------------------------------------------------------
// Compiled through the project's own Tailwind pipeline, so the utilities and
// the `@theme` tokens are generated by the same compiler the site uses.
const cssEntry = resolve(here, 'src/styles.css');
const css = await readFile(cssEntry, 'utf8');
const result = await postcss([tailwind()]).process(css, {
  from: cssEntry,
  to: resolve(dist, 'index.css'),
});
await writeFile(resolve(dist, 'index.css'), result.css, 'utf8');

// --- types ----------------------------------------------------------------
// Emitted from the real component source, so the contract a consumer codes
// against is the one the components actually implement.
execFileSync('npx', ['tsc', '-p', resolve(here, 'tsconfig.json')], { stdio: 'inherit' });

/*
 * One rewrite in the emitted declarations.
 *
 * `Button`'s anchor props are derived from `typeof Link`, so `tsc` emits
 * `import Link from 'next/link'` into the `.d.ts`. That resolves inside the
 * application and nowhere else — a consumer without Next installed gets a
 * broken type on the package's primary component. The import is repointed
 * at the same shim the bundle already uses, which is the anchor those props
 * describe anyway.
 */
const buttonTypes = resolve(dist, 'types/components/ui/Button.d.ts');
const original = await readFile(buttonTypes, 'utf8');
const repointed = original.replace(
  /^import Link from 'next\/link';$/m,
  "import type Link from '../../design-system/src/link';",
);
if (repointed === original) {
  throw new Error('Button.d.ts no longer imports next/link — check the rewrite is still needed');
}
await writeFile(buttonTypes, repointed, 'utf8');

console.log('primitives: dist/index.js, dist/index.css, dist/types/');
