import { PANORAMA_MANIFEST } from './manifest.generated';
import type { ManifestEntry } from './manifest-types';
import type { PanoramaSource } from './panoLoader';

/**
 * Which spaces have a rendered panorama.
 *
 * The list itself is generated by the render job — `manifest.generated.ts`,
 * emitted from what is actually on disk, so a room appears here when and
 * only when six faces exist for it. Nothing about the residence is asserted
 * by hand; a placeholder cubemap would put an invented interior in front of
 * a buyer, which is the one thing this project does not do.
 *
 * **Partial coverage is the designed normal, not an error.** Renders run per
 * room and take minutes each, so most of the time some rooms exist and some
 * do not. Every consumer treats a missing entry as "this room cannot be
 * entered yet" and shows nothing.
 */
const BY_ID: ReadonlyMap<string, ManifestEntry> = new Map(
  PANORAMA_MANIFEST.map((entry) => [entry.id, entry] as const),
);

export function panoramaFor(spaceId: string): PanoramaSource | null {
  const entry = BY_ID.get(spaceId);
  if (!entry) return null;
  return {
    kind: 'cube',
    // The space id, which is also the loader's cache key. The content hash
    // lives in `basePath`, so a rebuild gets a new immutable URL without
    // disturbing cache identity.
    id: entry.id,
    basePath: entry.basePath,
    extension: entry.extension,
  };
}

export function hasPanorama(spaceId: string): boolean {
  return BY_ID.has(spaceId);
}

/** Space ids with a rendered panorama, for coverage reporting. */
export function panoramaCoverage(): readonly string[] {
  return PANORAMA_MANIFEST.map((entry) => entry.id);
}
