// GENERATED by scripts/render-panoramas.mjs — do not edit.
// Regenerate with: npm run render:panoramas

import type { ManifestEntry } from './manifest-types';

export const PANORAMA_MANIFEST: readonly ManifestEntry[] = [];
