// GENERATED by scripts/render-panoramas.mjs — do not edit.
// Regenerate with: npm run render:panoramas

import type { ManifestEntry } from './manifest-types';

export const PANORAMA_MANIFEST: readonly ManifestEntry[] = [
  {
    "id": "bedroom2",
    "building": "residence",
    "quality": "traced",
    "hash": "c7d4609f695b",
    "basePath": "/assets/pano/residence/bedroom2/c7d4609f695b",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "dining",
    "building": "residence",
    "quality": "traced",
    "hash": "4d2e0280f553",
    "basePath": "/assets/pano/residence/dining/4d2e0280f553",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "dressing",
    "building": "residence",
    "quality": "traced",
    "hash": "38c498ece5a0",
    "basePath": "/assets/pano/residence/dressing/38c498ece5a0",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "foyer",
    "building": "residence",
    "quality": "traced",
    "hash": "873f50bf005c",
    "basePath": "/assets/pano/residence/foyer/873f50bf005c",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "guest",
    "building": "residence",
    "quality": "traced",
    "hash": "6f9af3e091fd",
    "basePath": "/assets/pano/residence/guest/6f9af3e091fd",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "kitchen",
    "building": "residence",
    "quality": "traced",
    "hash": "bce2e50975f7",
    "basePath": "/assets/pano/residence/kitchen/bce2e50975f7",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "library",
    "building": "residence",
    "quality": "traced",
    "hash": "9164bb46c526",
    "basePath": "/assets/pano/residence/library/9164bb46c526",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "living",
    "building": "residence",
    "quality": "traced",
    "hash": "0e5fa50f8d21",
    "basePath": "/assets/pano/residence/living/0e5fa50f8d21",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "master",
    "building": "residence",
    "quality": "traced",
    "hash": "32faebdc98c9",
    "basePath": "/assets/pano/residence/master/32faebdc98c9",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "masterBath",
    "building": "residence",
    "quality": "traced",
    "hash": "2d0d4e65f22e",
    "basePath": "/assets/pano/residence/masterBath/2d0d4e65f22e",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "stair",
    "building": "residence",
    "quality": "traced",
    "hash": "bfd5c4b21af2",
    "basePath": "/assets/pano/residence/stair/bfd5c4b21af2",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "study",
    "building": "residence",
    "quality": "traced",
    "hash": "209ae035b099",
    "basePath": "/assets/pano/residence/study/209ae035b099",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "upperLounge",
    "building": "residence",
    "quality": "traced",
    "hash": "25a73c33d34e",
    "basePath": "/assets/pano/residence/upperLounge/25a73c33d34e",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "atrium",
    "building": "tower",
    "quality": "raster",
    "hash": "216a181805d1",
    "basePath": "/assets/pano/tower/atrium/216a181805d1",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "balcony",
    "building": "tower",
    "quality": "raster",
    "hash": "000e6da5ba15",
    "basePath": "/assets/pano/tower/balcony/000e6da5ba15",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "bathroom",
    "building": "tower",
    "quality": "raster",
    "hash": "f9a9242ca62d",
    "basePath": "/assets/pano/tower/bathroom/f9a9242ca62d",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "bedroom",
    "building": "tower",
    "quality": "raster",
    "hash": "a00bb6dfdfc4",
    "basePath": "/assets/pano/tower/bedroom/a00bb6dfdfc4",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "cinema",
    "building": "tower",
    "quality": "raster",
    "hash": "af4c0e9c670e",
    "basePath": "/assets/pano/tower/cinema/af4c0e9c670e",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "foodHall",
    "building": "tower",
    "quality": "raster",
    "hash": "90512f1af717",
    "basePath": "/assets/pano/tower/foodHall/90512f1af717",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "gallery",
    "building": "tower",
    "quality": "raster",
    "hash": "3544a29291a9",
    "basePath": "/assets/pano/tower/gallery/3544a29291a9",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "gym",
    "building": "tower",
    "quality": "raster",
    "hash": "028003736485",
    "basePath": "/assets/pano/tower/gym/028003736485",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "kitchen",
    "building": "tower",
    "quality": "raster",
    "hash": "a4057aad6004",
    "basePath": "/assets/pano/tower/kitchen/a4057aad6004",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "lobby",
    "building": "tower",
    "quality": "raster",
    "hash": "8dfe5b347657",
    "basePath": "/assets/pano/tower/lobby/8dfe5b347657",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "residence",
    "building": "tower",
    "quality": "raster",
    "hash": "80c76c48d5bd",
    "basePath": "/assets/pano/tower/residence/80c76c48d5bd",
    "extension": "jpg",
    "size": 1024
  },
  {
    "id": "spa",
    "building": "tower",
    "quality": "raster",
    "hash": "0ef971000cb5",
    "basePath": "/assets/pano/tower/spa/0ef971000cb5",
    "extension": "jpg",
    "size": 1024
  }
];
